export const ALERT ={
    ALERT_ACCOUNT_LOGIN_FAIL:"Sai tài khoản hoặc mật khẩu",
    ALERT_SUCCESS:"ALERT_SUCCESS",
    ALERT_CLEAR:"ALERT_CLEAR",
    ALERT_REGISTRAITON_FAIL:"ALERT_REGISTRAITON_FAIL"
}