export const userType = {
    LOGIN:"LOGIN",
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FAIL:"LOGIN_FAIL",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",


    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_FAIL:"REGISTER_FAIL",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",



    
    LOGOUT:"LOGOUT",

    GETALL:"GETALL"
    
}