export const admin_Auth_type = {
    ADMIN_LOGIN_REQEST:"ADMIN_LOGIN_REQEST",
    ADMIN_LOGIN_FAILTURE:"ADMIN_LOGIN_FAILTURE",
    ADMIN_LOGIN_SUCCESS:"ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGOUT:"ADMIN_LOGOUT"
}